version: 2.1

orbs:
  docker: arribada/docker@0.0.11
workflows:
  publish:
    jobs:
      - docker/publish:
          containerName: packet-forwarder
          context: org-context
          filters:
            branches:
                only: 
                  - master
            #   ignore: /.*/
            # tags:
            #   only: /v\d+\.\d+\.\d+$/